# build configuration file
targets:
  osldr:
    efi_bootloader: true
    valid_arch: all
    sources:
      - osldr
      - atop
      - menu
      - libstd
  acpi:
    base_dir: acpidump
    sources:
      - acpidump
      - libstd
  hello:
    sources:
      - hello
  bgrt:
    sources:
      - bgrt
